--1.A
SELECT AE.EMP_NUM, AE.EMP_TITLE, AE.EMP_FNAME, AE.EMP_LNAME, P.PIL_LICENSE, P.PIL_RATINGS
FROM AVIA_EMPLOYEE AE, PILOT P
WHERE AE.EMP_NUM = P.EMP_NUM;

--1.B
SELECT AE.EMP_NUM, AE.EMP_TITLE, AE.EMP_FNAME, AE.EMP_LNAME, P.PIL_LICENSE, P.PIL_RATINGS
FROM AVIA_EMPLOYEE AE JOIN PILOT P
ON AE.EMP_NUM = P.EMP_NUM;

--2.A
SELECT AE.EMP_NUM, AE.EMP_TITLE, AE.EMP_FNAME, AE.EMP_LNAME, P.PIL_LICENSE, P.PIL_RATINGS
FROM AVIA_EMPLOYEE AE, PILOT P
WHERE AE.EMP_NUM = P.EMP_NUM(+);

--2.B
SELECT AE.EMP_NUM, AE.EMP_TITLE, AE.EMP_FNAME, AE.EMP_LNAME, P.PIL_LICENSE, P.PIL_RATINGS
FROM AVIA_EMPLOYEE AE LEFT JOIN PILOT P
ON AE.EMP_NUM = P.EMP_NUM;

--3.A
SELECT C.CHAR_DATE, CU.CUS_LNAME, CU.CUS_FNAME, CU.CUS_BALANCE, C.CHAR_TRIP, C.CHAR_DESTINATION, A.AC_NUMBER, A.MOD_CODE
FROM CHARTER C, AVIA_CUSTOMER CU, AIRCRAFT A
WHERE C.CUS_CODE = CU.CUS_CODE AND C.AC_NUMBER = A.AC_NUMBER AND CU.CUS_BALANCE>0
ORDER BY C.CHAR_DATE, CU.CUS_LNAME, CU.CUS_FNAME;

--3.B
SELECT C.CHAR_DATE, CU.CUS_LNAME, CU.CUS_FNAME, CU.CUS_BALANCE, C.CHAR_TRIP, C.CHAR_DESTINATION, A.AC_NUMBER, A.MOD_CODE
FROM CHARTER C JOIN AVIA_CUSTOMER CU
ON C.CUS_CODE = CU.CUS_CODE
JOIN AIRCRAFT A
ON C.AC_NUMBER = A.AC_NUMBER
WHERE CU.CUS_BALANCE>0
ORDER BY C.CHAR_DATE, CU.CUS_LNAME, CU.CUS_FNAME;

--4.A
SELECT A.AC_NUMBER, A.MOD_CODE, M.MOD_MANUFACTURER, A.AC_TTAF, A.AC_TTEL, A.AC_TTER, C.CHAR_TRIP, C.CHAR_DATE, C.CHAR_DESTINATION, C.CHAR_DISTANCE
FROM AIRCRAFT A, MODEL M, CHARTER C
WHERE A.MOD_CODE = M.MOD_CODE(+) AND A.AC_NUMBER = C.AC_NUMBER
ORDER BY A.AC_NUMBER;

--4.B
SELECT A.AC_NUMBER, A.MOD_CODE, M.MOD_MANUFACTURER, A.AC_TTAF, A.AC_TTEL, A.AC_TTER, C.CHAR_TRIP, C.CHAR_DATE, C.CHAR_DESTINATION, C.CHAR_DISTANCE
FROM AIRCRAFT A LEFT JOIN MODEL M
ON A.MOD_CODE = M.MOD_CODE
JOIN CHARTER C
ON A.AC_NUMBER = C.AC_NUMBER
ORDER BY A.AC_NUMBER;

--5.A
SELECT CH.CHAR_DATE, CH.AC_NUMBER, CH.CHAR_DESTINATION, CH.CHAR_DISTANCE, AE.EMP_LNAME, AE.EMP_FNAME, C.CREW_JOB
FROM CREW C, CHARTER CH, AVIA_EMPLOYEE AE
WHERE C.CHAR_TRIP = CH.CHAR_TRIP AND C.EMP_NUM = AE.EMP_NUM AND CH.CHAR_DATE = '07-FEB-13';

--5.B
SELECT CH.CHAR_DATE, CH.AC_NUMBER, CH.CHAR_DESTINATION, CH.CHAR_DISTANCE, AE.EMP_LNAME, AE.EMP_FNAME, C.CREW_JOB
FROM CHARTER CH JOIN CREW C
ON C.CHAR_TRIP = CH.CHAR_TRIP
JOIN AVIA_EMPLOYEE AE
ON C.EMP_NUM = AE.EMP_NUM
WHERE CH.CHAR_DATE = '07-FEB-13';

--6.A
INSERT INTO RATING
VALUES ('MES', 'Multiengine Sea');

--6.B
SELECT AE.EMP_NUM,
CONCAT(CONCAT(CONCAT(CONCAT(AE.EMP_TITLE, ' '), AE.EMP_FNAME), ', '), AE.EMP_LNAME) AS EMPLOYEE,
AE.EMP_HIRE_DATE,
FLOOR(MONTHS_BETWEEN(SYSDATE, AE.EMP_DOB)/12) AS AGE,
R.RTG_CODE,
R.RTG_NAME,
ER.EARNRTG_DATE,
P.PIL_LICENSE,
P.PIL_RATINGS
FROM AVIA_EMPLOYEE AE
FULL OUTER JOIN EARNEDRATING ER 
       ON AE.EMP_NUM = ER.EMP_NUM
FULL OUTER JOIN RATING R 
       ON ER.RTG_CODE = R.RTG_CODE
LEFT JOIN PILOT P 
       ON AE.EMP_NUM = P.EMP_NUM
ORDER BY EMPLOYEE, R.RTG_CODE;